# https://docs.docker.com/compose/yml/
#

name: 'es-examples'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.1
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elastic:9200
    depends_on:
      - elastic
